import { sql } from 'drizzle-orm';
import type { NodePgDatabase } from 'drizzle-orm/node-postgres';
import type { RunState, GateKind, Lane } from '@kanal/contracts';
import { TRANSITIONS, LANE_CONFIG, TERMINAL_STATES, INTERRUPT_STATES, type Transition } from './transitions.js';
import { enqueueJob } from './queue.js';

/**
 * The Runner seam (plan §12.2). Everything above the runtime — the API, the
 * UI, the pipeline stages — talks to this interface. `PgRunner` is the V1
 * implementation; a `TemporalRunner` would be a second implementation.
 */
export interface Runner {
  start(input: StartRunInput): Promise<RunHandle>;
  signal(runId: string, sig: RunSignal): Promise<void>;
  cancel(runId: string, reason: string): Promise<void>;
  describe(runId: string): Promise<RunSnapshot>;
}

export interface StartRunInput {
  orgId: string;
  channelId: string;
  lane: Lane;
  brief: Record<string, unknown>;
  manifestSetHash: string;
  promptPackVersion: string;
  budgetCapUsd: number;
}

export interface RunHandle {
  runId: string;
}

export type RunSignal =
  | { kind: 'approval'; gate: GateKind; decision: 'granted' | 'denied'; decidedBy: string; note?: string }
  | { kind: 'lane_change'; lane: Lane }
  | { kind: 'cancel' }
  | { kind: 'resume' };

export interface RunSnapshot {
  runId: string;
  orgId: string;
  state: RunState;
  cursorStage: string;
  lane: Lane;
  spentUsd: number;
  budgetCapUsd: number;
  cancelRequested: boolean;
  steps: Array<{ stage: string; attempt: number; state: string }>;
}

const RUN_STATE_COL = sql.raw('state');

/**
 * Postgres-backed durable runner. A run is (run.state, run.cursor, run_step[]);
 * workers hold no run state in memory. Every step is a row inserted before the
 * side effect and updated after, keyed by (run_id, stage, attempt).
 */
export class PgRunner implements Runner {
  constructor(private readonly db: NodePgDatabase) {}

  async start(input: StartRunInput): Promise<RunHandle> {
    // uuidv7() is generated by the DB default
    const rows = await this.db.execute(sql`
      INSERT INTO run (org_id, channel_id, lane, state, cursor_stage, brief,
                       manifest_set_hash, prompt_pack_version, trace_id,
                       budget_cap_usd, spent_usd, cancel_requested)
      VALUES (${input.orgId}, ${input.channelId}, ${input.lane}, 'intake', 'intake',
              ${JSON.stringify(input.brief)}::jsonb, ${input.manifestSetHash},
              ${input.promptPackVersion}, gen_random_uuid()::text, ${input.budgetCapUsd}, 0, false)
      RETURNING id;
    `);
    const handle = rows.rows[0] as unknown as { id: string };
    // enqueue the first pipeline job
    await enqueueJob(this.db, {
      orgId: input.orgId,
      queue: 'pipeline',
      singletonKey: `pipeline:${handle.id}`,
      payload: { runId: handle.id, stage: 'intake' },
    });
    return { runId: handle.id };
  }

  async signal(runId: string, sig: RunSignal): Promise<void> {
    if (sig.kind === 'cancel') {
      await this.cancel(runId, 'cancel signal');
      return;
    }
    if (sig.kind === 'lane_change') {
      await this.db.execute(sql`
        UPDATE run SET lane=${sig.lane} WHERE id=${runId};
      `);
      // lane change appends a lane_change row and sets a cancellation flag the
      // current step polls at every await point (plan §5.4)
      await this.db.execute(sql`
        INSERT INTO audit_event (org_id, actor, verb, object_ref, after)
        SELECT org_id, 'human:operator', 'lane_change', ${runId}, jsonb_build_object('lane', ${sig.lane})
        FROM run WHERE id=${runId};
      `);
      return;
    }
    if (sig.kind === 'resume') {
      const rows = await this.db.execute(sql`SELECT state FROM run WHERE id=${runId}`);
      const row = rows.rows[0] as unknown as { state: RunState } | undefined;
      if (row && INTERRUPT_STATES.includes(row.state)) {
        await this.resumeFrom(row.state, runId);
      }
      return;
    }
    // approval decision
    if (sig.kind === 'approval') {
      const state = sig.decision === 'granted' ? 'granted' : 'denied';
      await this.db.execute(sql`
        UPDATE approval SET state=${state}, decided_by=${sig.decidedBy}, decided_at=now()
        WHERE run_id=${runId} AND gate=${sig.gate} AND state='pending';
      `);
      if (sig.decision === 'granted') {
        await this.resumeFrom('review_pending', runId);
      } else {
        // denial moves the run away from publishing (plan §4.1 #4)
        await this.db.execute(sql`UPDATE run SET state='cancelled', finished_at=now() WHERE id=${runId}`);
      }
    }
  }

  private async resumeFrom(state: RunState, runId: string): Promise<void> {
    const t = findTransition(state, 'human_approve') ?? findTransition(state, 'human_claims_run') ?? findTransition(state, 'human_override');
    if (t) {
      await this.db.execute(sql`UPDATE run SET state=${t.to} WHERE id=${runId}`);
    }
    await this.enqueueNextStep(runId);
  }

  async cancel(runId: string, reason: string): Promise<void> {
    await this.db.execute(sql`
      UPDATE run SET state='cancelled', finished_at=now(), error_detail=${reason} WHERE id=${runId};
    `);
  }

  async describe(runId: string): Promise<RunSnapshot> {
    const runRows = await this.db.execute(sql`
      SELECT id, org_id, state, cursor_stage, lane, spent_usd, budget_cap_usd, cancel_requested
      FROM run WHERE id=${runId};
    `);
    const r = runRows.rows[0] as unknown as {
      id: string; org_id: string; state: RunState; cursor_stage: string; lane: Lane;
      spent_usd: number; budget_cap_usd: number; cancel_requested: boolean;
    };
    const stepRows = await this.db.execute(sql`
      SELECT stage, attempt, state FROM run_step WHERE run_id=${runId} ORDER BY started_at;
    `);
    const steps = (stepRows as unknown as Array<{ stage: string; attempt: number; state: string }>).map((s) => ({
      stage: s.stage, attempt: s.attempt, state: s.state,
    }));
    return {
      runId: r.id,
      orgId: r.org_id,
      state: r.state,
      cursorStage: r.cursor_stage,
      lane: r.lane,
      spentUsd: Number(r.spent_usd),
      budgetCapUsd: Number(r.budget_cap_usd),
      cancelRequested: r.cancel_requested,
      steps,
    };
  }

  /**
   * The pipeline executor: given a run id and the stage to run next, applies
   * the transition table, runs the stage, and enqueues the next step. Called
   * by worker-pipeline. Idempotency is enforced by run_step.idempotency_key.
   */
  async advance(runId: string, event: string): Promise<void> {
    const snap = await this.describe(runId);
    if (TERMINAL_STATES.includes(snap.state)) return;
    const t = findTransition(snap.state, event);
    if (!t) return;
    // Lane gate filtering (plan §5.1): the lane config decides which gates are
    // human-gated. A gate that is on for this lane parks the run for approval.
    if (t.gate && this.needsHumanGate(t.gate, snap.lane)) {
      await this.requestApproval(runId, snap.orgId, t);
      return;
    }
    await this.applyTransition(t, runId);
    await this.enqueueNextStep(runId);
  }

  private needsHumanGate(gate: GateKind, lane: Lane): boolean {
    const cfg = LANE_CONFIG[lane];
    if (gate === 'topic') return cfg.gates.topic;
    if (gate === 'draft') return cfg.gates.draft;
    if (gate === 'publish') return cfg.gates.publish;
    return true;
  }

  private async requestApproval(runId: string, orgId: string, t: Transition): Promise<void> {
    if (!t.gate) return;
    // the approval row is the only live object; the run parks
    await this.db.execute(sql`UPDATE run SET state='review_pending' WHERE id=${runId}`);
    await this.db.execute(sql`
      INSERT INTO approval (org_id, run_id, gate, payload_hash, state, sla_deadline, hard_expiry)
      SELECT ${orgId}, ${runId}, ${t.gate}, gen_random_uuid()::text, 'pending',
             now() + interval '4 hours', now() + interval '72 hours'
      ON CONFLICT DO NOTHING;
    `);
  }

  private async applyTransition(t: Transition, runId: string): Promise<void> {
    await this.db.execute(sql`
      UPDATE run SET state=${t.to}, cursor_stage=${t.event} WHERE id=${runId};
    `);
  }

  private async enqueueNextStep(runId: string): Promise<void> {
    const snap = await this.describe(runId);
    if (TERMINAL_STATES.includes(snap.state)) return;
    await enqueueJob(this.db, {
      orgId: snap.orgId,
      queue: 'pipeline',
      singletonKey: `pipeline:${runId}`,
      payload: { runId, state: snap.state },
    });
  }
}

function findTransition(from: RunState, event: string): Transition | undefined {
  return TRANSITIONS.find((t) => t.from === from && t.event === event);
}

void RUN_STATE_COL;
